### ISSUE TITLE
Find out how to integrate phantomjs & browser runner

### ISSUE THREAD

**Issue by cburgmer** [cburgmer/csscritic#19]
Tests for the console runner (phantomjs) are currently signed of via fingerprints, in the browser via a click on "accept". Does it make sense to integrate both solutions? How can this be done?

**Comment by SamHasler** [comment]
A solution that kept storage in the file system so that it can be shared between developers would be better. Could it just store fingerprints of reference images (i.e. their MD5 checksum) so that they could be committed to vcs without bloating the repo?

**Comment by cburgmer** [comment]
Hey there, thanks for the feedback (including the other issues).

I've thought long and hard on moving forward towards inclusion in a build pipeline (i.e. cli runner + shared accepting of tests).

Propagating a reference image is difficult if you consider different browser versions, different user agents, OSes or fonts installed. Unless your CI environment and those pushing to it use the same setup, you will see differences in the rendered image.

I have so far stayed away from using reference images as means to mark a "green" test, not because of file size, but as any browser will have their own interpretation of an HTML document, all of them being correct. One single image cannot capture this fact.

The phantomjs runner was an experiment to fix an accepted ("green") test with the hash of the complete document (including JS, CSS + images). However currently any change needs a manual process to update the reference hash. This is in no way ready for a CI process.

CSS Critic, in my eyes, has currently evolved towards a lean tool with very quick feedback in the browser. I'd like to focus the tool on becoming even better in that regard. If I continue on the road with document hashing any CLI approach will probably be outside of this project's focus.

**Comment by SamHasler** [comment]
I hadn't realised it wasn't using reference images, and was only fingerprinting the documents. Now that I've had time to think on it some more just having the fingerprint of a reference image wouldn't be enough, because you couldn't show a perceptual diff.

I'm looking for something that does pdiffs thats less complex to set up than https://github.com/bslatkin/dpxdt, https://github.com/Huddle/PhantomCSS or https://github.com/BBC-News/wraith and has a built in workflow for approving changes. Csscritic is almost perfect apart from storing the reference images in the browser. I'd like to be able to share reference images with the rest of the team, particularly QA.

I think it shouldn't be too hard to replace csscriticLib.indexeddbstorage with something that read/writes to https://github.com/typicode/json-server so I'll probably have a go at hacking something simple together, possibly also storing the user agent and allowing storing separate reference images for different browsers.

**Comment by cburgmer** [comment]
Yes, replacing the current storage with something that stores on the file system is doable, and I think you already found https://github.com/cburgmer/csscritic/blob/master/src/browser/indexedDbStorage.js which is a good reference for what the current interface is. This is all wired together in https://github.com/cburgmer/csscritic/blob/master/src/boot/browser.js.

If you want to store images in Git then https://git-lfs.github.com might be interesting.

My fair warning: The images will depend on your and everybody else's environment.

**Comment by cburgmer** [comment]
Closing as I'm not planning to bring this forward.
